# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: operator.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='operator.proto',
  package='operatorproto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eoperator.proto\x12\roperatorproto\"*\n\x05Shape\x12\x11\n\tdimension\x18\x01 \x03(\x05\x12\x0e\n\x06stride\x18\x02 \x03(\x05\"\xbf\x01\n\x06Tensor\x12+\n\x06layout\x18\x01 \x01(\x0e\x32\x1b.operatorproto.TensorLayout\x12)\n\x08\x64\x61tatype\x18\x02 \x01(\x0e\x32\x17.operatorproto.DataType\x12#\n\x05shape\x18\x03 \x01(\x0b\x32\x14.operatorproto.Shape\x12\x12\n\nvalueFloat\x18\x04 \x03(\x02\x12\x12\n\nvalueInt32\x18\x05 \x03(\x05\x12\x10\n\x08valueHex\x18\x06 \x03(\t\"\x8e\x01\n\x08Operator\x12\x0c\n\x04name\x18\x01 \x01(\t\x12%\n\x06\x64\x65vice\x18\x02 \x01(\x0e\x32\x15.operatorproto.Device\x12%\n\x06inputs\x18\x03 \x03(\x0b\x32\x15.operatorproto.Tensor\x12&\n\x07outputs\x18\x04 \x03(\x0b\x32\x15.operatorproto.Tensor*V\n\x0cTensorLayout\x12\x12\n\x0eLAYOUT_UNKNOWN\x10\x00\x12\x0f\n\x0bLAYOUT_NCHW\x10\x01\x12\x0f\n\x0bLAYOUT_NHWC\x10\x02\x12\x10\n\x0cLAYOUT_ARRAY\x10\x03*O\n\x08\x44\x61taType\x12\x11\n\rDTYPE_UNKNOWN\x10\x00\x12\x0e\n\nDTYPE_HALF\x10\x01\x12\x0f\n\x0b\x44TYPE_FLOAT\x10\x02\x12\x0f\n\x0b\x44TYPE_INT32\x10\x03*L\n\x06\x44\x65vice\x12\x12\n\x0e\x44\x45VICE_UNKNOWN\x10\x00\x12\x0e\n\nDEVICE_CPU\x10\x01\x12\x0e\n\nDEVICE_GPU\x10\x02\x12\x0e\n\nDEVICE_MLU\x10\x03\x62\x06proto3'
)

_TENSORLAYOUT = _descriptor.EnumDescriptor(
  name='TensorLayout',
  full_name='operatorproto.TensorLayout',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LAYOUT_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LAYOUT_NCHW', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LAYOUT_NHWC', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LAYOUT_ARRAY', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=416,
  serialized_end=502,
)
_sym_db.RegisterEnumDescriptor(_TENSORLAYOUT)

TensorLayout = enum_type_wrapper.EnumTypeWrapper(_TENSORLAYOUT)
_DATATYPE = _descriptor.EnumDescriptor(
  name='DataType',
  full_name='operatorproto.DataType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DTYPE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DTYPE_HALF', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DTYPE_FLOAT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DTYPE_INT32', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=504,
  serialized_end=583,
)
_sym_db.RegisterEnumDescriptor(_DATATYPE)

DataType = enum_type_wrapper.EnumTypeWrapper(_DATATYPE)
_DEVICE = _descriptor.EnumDescriptor(
  name='Device',
  full_name='operatorproto.Device',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DEVICE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DEVICE_CPU', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DEVICE_GPU', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DEVICE_MLU', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=585,
  serialized_end=661,
)
_sym_db.RegisterEnumDescriptor(_DEVICE)

Device = enum_type_wrapper.EnumTypeWrapper(_DEVICE)
LAYOUT_UNKNOWN = 0
LAYOUT_NCHW = 1
LAYOUT_NHWC = 2
LAYOUT_ARRAY = 3
DTYPE_UNKNOWN = 0
DTYPE_HALF = 1
DTYPE_FLOAT = 2
DTYPE_INT32 = 3
DEVICE_UNKNOWN = 0
DEVICE_CPU = 1
DEVICE_GPU = 2
DEVICE_MLU = 3



_SHAPE = _descriptor.Descriptor(
  name='Shape',
  full_name='operatorproto.Shape',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dimension', full_name='operatorproto.Shape.dimension', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stride', full_name='operatorproto.Shape.stride', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=75,
)


_TENSOR = _descriptor.Descriptor(
  name='Tensor',
  full_name='operatorproto.Tensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='layout', full_name='operatorproto.Tensor.layout', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='datatype', full_name='operatorproto.Tensor.datatype', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shape', full_name='operatorproto.Tensor.shape', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='valueFloat', full_name='operatorproto.Tensor.valueFloat', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='valueInt32', full_name='operatorproto.Tensor.valueInt32', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='valueHex', full_name='operatorproto.Tensor.valueHex', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=269,
)


_OPERATOR = _descriptor.Descriptor(
  name='Operator',
  full_name='operatorproto.Operator',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='operatorproto.Operator.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device', full_name='operatorproto.Operator.device', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='inputs', full_name='operatorproto.Operator.inputs', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='outputs', full_name='operatorproto.Operator.outputs', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=414,
)

_TENSOR.fields_by_name['layout'].enum_type = _TENSORLAYOUT
_TENSOR.fields_by_name['datatype'].enum_type = _DATATYPE
_TENSOR.fields_by_name['shape'].message_type = _SHAPE
_OPERATOR.fields_by_name['device'].enum_type = _DEVICE
_OPERATOR.fields_by_name['inputs'].message_type = _TENSOR
_OPERATOR.fields_by_name['outputs'].message_type = _TENSOR
DESCRIPTOR.message_types_by_name['Shape'] = _SHAPE
DESCRIPTOR.message_types_by_name['Tensor'] = _TENSOR
DESCRIPTOR.message_types_by_name['Operator'] = _OPERATOR
DESCRIPTOR.enum_types_by_name['TensorLayout'] = _TENSORLAYOUT
DESCRIPTOR.enum_types_by_name['DataType'] = _DATATYPE
DESCRIPTOR.enum_types_by_name['Device'] = _DEVICE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Shape = _reflection.GeneratedProtocolMessageType('Shape', (_message.Message,), {
  'DESCRIPTOR' : _SHAPE,
  '__module__' : 'operator_pb2'
  # @@protoc_insertion_point(class_scope:operatorproto.Shape)
  })
_sym_db.RegisterMessage(Shape)

Tensor = _reflection.GeneratedProtocolMessageType('Tensor', (_message.Message,), {
  'DESCRIPTOR' : _TENSOR,
  '__module__' : 'operator_pb2'
  # @@protoc_insertion_point(class_scope:operatorproto.Tensor)
  })
_sym_db.RegisterMessage(Tensor)

Operator = _reflection.GeneratedProtocolMessageType('Operator', (_message.Message,), {
  'DESCRIPTOR' : _OPERATOR,
  '__module__' : 'operator_pb2'
  # @@protoc_insertion_point(class_scope:operatorproto.Operator)
  })
_sym_db.RegisterMessage(Operator)


# @@protoc_insertion_point(module_scope)
