sample: sample.cpp transpose.cc
	g++ -I../../include sample.cpp transpose.cc -o sample -std=c++11 -O3
	
dilated: dilated_sample.cpp transpose.cc
	g++ -I../../include dilated_sample.cpp transpose.cc -o dilated -std=c++11 -O3
